create type tweetsType as closed {
  id: uuid,
  terms: double,
  topics: double,
  tags: double,
  links: double,
  sentiment: double,
  class: string
};
create dataset tweetsDataset(tweetsType)
primary key id autogenerated;