create type weatherType as closed {
  id: uuid,
  outlook: string,
  temperature: double,
  humidity: double,
  windy: string,
  play: string
};
create dataset weatherDataset(weatherType)
primary key id autogenerated;